### ISSUE TITLE
Invalid values for the duration and the frame count of streams

### ISSUE THREAD

**Issue by dogamak** [meh/rust-ffmpeg#83]
Both my code and the `examples/metadata.rs` provided in this repository are giving me erroneous values for the duration of the streams and the count of frames in the streams.

A count of `0` frames and a duration of `-9223372036854775808` seconds(?) is returned for all inputs.

Aside from these two values everything seems to work so far, `examples/metadata.rs` outputs correct information and I was able to create thumbnails successfully from the video files. (Although not from the correct timestamps for the reason above)

Ffprobe, however, displays the correct figures for these fields. Ffmpeg and associated libraries' versions are listed below:
```
ffmpeg version 3.3.1 Copyright (c) 2000-2017 the FFmpeg developers                                                                                             
built with gcc 7.1.1 (GCC) 20170516
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-shared --enable-version3
libavutil      55. 58.100 / 55. 58.100
libavcodec     57. 89.100 / 57. 89.100
libavformat    57. 71.100 / 57. 71.100
libavdevice    57.  6.100 / 57.  6.100
libavfilter     6. 82.100 /  6. 82.100
libavresample   3.  5.  0 /  3.  5.  0
libswscale      4.  6.100 /  4.  6.100
libswresample   2.  7.100 /  2.  7.100
libpostproc    54.  5.100 / 54.  5.100
```

If needed, I put my own code up in a gist [here](https://gist.github.com/dogamak/8068448e285803c40e845866e72aa507), but beware that it is the aftermath of tons of trial and error and debugging with `println!` and so it is rather crude.

**Comment by meh** [comment]
Can you try with ffmpeg 3.2? It sounds like a mismatch between the shape of structs used by ffmpeg-sys, there's a bindgen based pull request on hold on ffmpeg-sys that should fix this kind of issue in the future.

**Comment by dogamak** [comment]
Hi, thanks for the super fast response.

I tried compiling with the `build` feature, which should fetch and build ffmpeg version `3.2` for me since I am using `v3.2.1` of `rust-ffmpeg-sys`, right?

With this, the result of `ffmpeg::libavfilter::version()` changed from `414308` to `409956` (how should these be interpreted?), but I am still experiencing the same issues.

**Comment by meh** [comment]
Yeah, `build` should do that. I guess it's still a shape mismatch somewhere, it's the only reason I can come up with for those values.

I'd wait for the bindgen changes, that should help out.
